version: '3.8'

services:
    database:
        image: browsebox-mysql
        container_name: browsebox-database
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: browsebox
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - .:/database/var/lib/mysql
        ports:
            - 3306:3306
        restart: always
